"""remove modo_pago

Revision ID: 1ca65b5b2b15
Revises: d7deee75f050
Create Date: 2026-05-17 16:31:47.356456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1ca65b5b2b15'
down_revision: Union[str, Sequence[str], None] = 'd7deee75f050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('importacionautomatica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tipo_entidad', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('documento_identidad', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('datos', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('fecha_ingreso', sa.DateTime(), nullable=False),
    sa.Column('observacion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('rol', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('contrasenia', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('tabla_nombre', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('operacion', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('valor_anterior', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valor_nuevo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_accion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalleactividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('actividad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividad.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tipo_inventario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('estado_objeto', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('observacion', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True),
    sa.ForeignKeyConstraint(['tipo_inventario_id'], ['tipoinventario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rectoriaestado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('motivo_estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['docente_id'], ['docente.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rectoriaobservaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=False),
    sa.Column('tipo_observacion', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['docente_id'], ['docente.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cafeteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('estado_cafeteria', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalleescuelaformacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('complementario_id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('mes', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('estado_escuela', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['complementario_id'], ['complementario.id'], ),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalleprueba',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('complementario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_prueba', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['complementario_id'], ['complementario.id'], ),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('tipo_incidencia', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prestamo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('inventario_id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('fecha_salida', sa.DateTime(), nullable=False),
    sa.Column('fecha_devolucion', sa.DateTime(), nullable=False),
    sa.Column('estado_prestamo', sa.Boolean(), nullable=False),
    sa.Column('observacion', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.id'], ),
    sa.ForeignKeyConstraint(['inventario_id'], ['inventario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pupitre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('estado_pupitre', sa.Boolean(), nullable=False),
    sa.Column('observacion', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detallepazysalvo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('prestamo_id', sa.Integer(), nullable=False),
    sa.Column('cafeteria_id', sa.Integer(), nullable=False),
    sa.Column('matricula_id', sa.Integer(), nullable=False),
    sa.Column('pension_id', sa.Integer(), nullable=False),
    sa.Column('pupitre_id', sa.Integer(), nullable=False),
    sa.Column('complemento_id', sa.Integer(), nullable=False),
    sa.Column('estado_escuela', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cafeteria_id'], ['cafeteria.id'], ),
    sa.ForeignKeyConstraint(['complemento_id'], ['complementario.id'], ),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.id'], ),
    sa.ForeignKeyConstraint(['matricula_id'], ['matricula.id'], ),
    sa.ForeignKeyConstraint(['pension_id'], ['pension.id'], ),
    sa.ForeignKeyConstraint(['prestamo_id'], ['prestamo.id'], ),
    sa.ForeignKeyConstraint(['pupitre_id'], ['pupitre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pazysalvo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('detalle_pazysalvo_id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('estado_final', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('observacion', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True),
    sa.ForeignKeyConstraint(['detalle_pazysalvo_id'], ['detallepazysalvo.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('pago', 'modo_pago')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pago', sa.Column('modo_pago', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_table('pazysalvo')
    op.drop_table('detallepazysalvo')
    op.drop_table('pupitre')
    op.drop_table('prestamo')
    op.drop_table('observador')
    op.drop_table('detalleprueba')
    op.drop_table('detalleescuelaformacion')
    op.drop_table('cafeteria')
    op.drop_table('rectoriaobservaciones')
    op.drop_table('rectoriaestado')
    op.drop_table('inventario')
    op.drop_table('detalleactividades')
    op.drop_table('auditoria')
    op.drop_table('usuario')
    op.drop_table('importacionautomatica')
    op.drop_table('actividad')
    # ### end Alembic commands ###
