"""remove valor_pendiente_pension

Revision ID: 997ee737cdc8
Revises: 1ca65b5b2b15
Create Date: 2026-05-17 16:53:58.382814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '997ee737cdc8'
down_revision: Union[str, Sequence[str], None] = '1ca65b5b2b15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matricula', 'valor_pendiente_pension')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matricula', sa.Column('valor_pendiente_pension', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
