"""estado_matricula_str_semaforo

Revision ID: fafba11702b3
Revises: 997ee737cdc8
Create Date: 2026-05-20 13:18:14.154722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fafba11702b3'
down_revision: Union[str, Sequence[str], None] = '997ee737cdc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matricula', 'estado_matricula',
               existing_type=sa.BOOLEAN(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matricula', 'estado_matricula',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    # ### end Alembic commands ###
